import type { StoredAuditReportReview } from "@/lib/audit-report-types";
import { partitionFactors } from "@/lib/recommendation-rationale";

export function AdminAuditReportReview({ review }: { review: StoredAuditReportReview }) {
  const { concerns, strengths } = partitionFactors(review.factors);

  return (
    <section className="flex flex-col gap-6 rounded-xl border border-sky-200 bg-sky-50/40 p-6 dark:border-sky-900/60 dark:bg-sky-950/20">
      <div>
        <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">Audit report review</h2>
        <p className="mt-1 text-xs text-zinc-600 dark:text-zinc-400">
          Generated by AI ({review.model}) from <strong>{review.fileName}</strong>. Validate scope, dates, and
          exceptions against the original report before relying on this summary.
        </p>
      </div>

      <div className="rounded-lg border border-sky-200 bg-white px-4 py-3 dark:border-sky-900 dark:bg-zinc-950/50">
        <p className="text-xs font-medium uppercase tracking-wide text-sky-800 dark:text-sky-300">
          Compliance posture
        </p>
        <p className="mt-1 text-sm font-medium text-zinc-900 dark:text-zinc-100">{review.compliancePosture}</p>
      </div>

      <div>
        <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Executive summary</h3>
        <p className="mt-2 text-sm leading-relaxed text-zinc-700 dark:text-zinc-200">{review.summary}</p>
      </div>

      <div>
        <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Institutional read</h3>
        <p className="mt-2 text-sm leading-relaxed text-zinc-700 dark:text-zinc-200">
          {review.institutionalInterpretation}
        </p>
      </div>

      <div className="rounded-lg border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm leading-relaxed text-zinc-800 dark:border-zinc-700 dark:bg-zinc-950/50 dark:text-zinc-100">
        {review.recommendationRationale}
      </div>

      <div>
        <h3 className="text-sm font-semibold text-amber-900 dark:text-amber-200">
          Audit concerns ({concerns.length})
        </h3>
        {concerns.length === 0 ? (
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">No specific concerns flagged in the audit report.</p>
        ) : (
          <ol className="mt-3 flex list-decimal flex-col gap-3 pl-5">
            {concerns.map((f, i) => (
              <li
                key={`${f.title}-${i}`}
                className="rounded-lg border border-amber-200 bg-amber-50/80 px-4 py-3 text-sm dark:border-amber-900/60 dark:bg-amber-950/30"
              >
                <p className="font-medium text-zinc-900 dark:text-zinc-100">{f.title}</p>
                <p className="mt-1 leading-relaxed text-zinc-700 dark:text-zinc-200">{f.detail}</p>
              </li>
            ))}
          </ol>
        )}
      </div>

      <div>
        <h3 className="text-sm font-semibold text-emerald-900 dark:text-emerald-200">
          Audit strengths ({strengths.length})
        </h3>
        {strengths.length === 0 ? (
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">No supporting controls highlighted in the audit report.</p>
        ) : (
          <ol className="mt-3 flex list-decimal flex-col gap-3 pl-5">
            {strengths.map((f, i) => (
              <li
                key={`${f.title}-${i}`}
                className="rounded-lg border border-emerald-200 bg-emerald-50/80 px-4 py-3 text-sm dark:border-emerald-900/60 dark:bg-emerald-950/30"
              >
                <p className="font-medium text-zinc-900 dark:text-zinc-100">{f.title}</p>
                <p className="mt-1 leading-relaxed text-zinc-700 dark:text-zinc-200">{f.detail}</p>
              </li>
            ))}
          </ol>
        )}
      </div>
    </section>
  );
}
